config/routes.rb
Rails.application.routes.draw do
  root "employees#index"
  resources :policies
  resources :companies do
    collection do 
      get "onboard_employees_index"	
      post "onboard_company_employees"	
    end	
  end
  resources :employees

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees
  has_many :policies
  validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def onboard_employees_index
    @companies = Company.all
  end

  def onboard_company_employees
    require 'csv'  
    file = params[:resume]
    @arr1 = [] 
    @company = Company.find(params[:company_id])
    @employees = @company.employees
    CSV.foreach(file.path, headers: true, encoding:'iso-8859-1:utf-8' ) do |row|
      binding.pry
      employee_name = row["Employee Name"]
      email = row["Email"]
      phone = row["Phone"]
      supervisior = row["Report To"]
      policies.split = row["Assigned Policies"]
      policies_arr = policies.split("|") rescue []
      employee = @employees.find_or_initialize_by(email: "vivek.ucek@gmail.com")
      employee.name = phone
      employee.phone = phone
      employee.parent_id = @employees.find_by(email: supervisior).id rescue nil
      employee.save
    end  

    respond_to do |format|
      format.html { redirect_to onboard_employees_index_companies_path, notice: 'Employee Onboarding has completed successfully' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/views/companies/onboard_employees_index.html.erb
<div class="col-md-12">
  <div class="panel panel-primary">
  	<div class="panel-heading">
      <h3 class="panel-title">Onboard Employees</h3>
  	</div>
  	<div class="panel-body" style="border:1px solid #536889;">

  	  <%= form_tag onboard_company_employees_companies_path, :class=>"form-inline" ,:role=>"form", method: 'POST', :id=>"onboard_form", :multipart => true, :remote => true do %>
  	
	  	<div class="col-sm-12" style="margin-top: 20px;"> 
		  <div class="form-group">
	      	<label for="role" class="col-sm-6 control-label">Select a Company <span style="color:red;"> *</span></label> 
	      	<div class="col-sm-6">   
	          <%= select_tag "company_id", options_from_collection_for_select(@companies, :id, :name),  {:class=>"form-control",  :required => true , :style => "width:100%;", :id => "company_id", :prompt => "Please Select Company"}  %>
	      	</div>
		  </div>  
	    </div>

	    <div class="col-sm-12" style="margin-top: 20px;"> 
		  <div class="form-group">
		    <label for="role" class="col-sm-6 control-label">Upload Resume <span style="color:red;"> *</span></label>
		    <div class="col-sm-6">          
		      <%= file_field_tag "resume", :id=>"xls_upload" %>
		      <br/><br/>
		      <span class="help-block">
		        (Select only .csv file)
              </span>
		    </div>       
		  </div>
	    </div>

	    <div class="col-sm-12" style="text-align: center;margin-top: 20px;">
	        <!-- <button type="submit" class="btn btn-info btn-trans btn-sm" id = "validate_fields" ><i class='fa fa-filter'></i>Upload Employees</button> -->
	   
	         <%= button_tag "Upload Employees", :class=>"btn btn-info btn-trans btn-sm", :data => {:disable_with => "<i class='fa fa-spinner fa-spin'></i> Processing".html_safe} do %>
              <i class='fa fa-laptop' style="float: right;margin-left: -20px;color: white;font-weight: 600;"></i> <span style="    margin-left: 20px;color: white;font-weight: 600;">Upload Employees</span>
            <% end %>     

	    </div>

      <% end %>
    </div>
  </div>
</div>